#!/usr/bin/env python
r"""Run an adiabatic-electron GKX heat-flux scan on an optimized wout.

The positional argument is a NEOPAX optimization output directory containing
``optimized/wout_*.nc``.  By default the requested surface labels are treated
as :math:`\rho=\sqrt{s}`, while GKX's ``geometry.torflux`` input is populated
with :math:`s=\rho^2`.

Each surface has an independent, restartable run directory.  After the runs,
the script writes a long-form flux-history CSV, a radial summary CSV, and a
two-panel heat-flux figure containing all requested radii.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
from pathlib import Path
import subprocess
import sys
import tomllib
from typing import Any


DEFAULT_RADII = (0.1, 0.3, 0.5, 0.7, 0.9)


def _toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    raise TypeError(f"Unsupported TOML value: {value!r}")


def _toml_text(data: dict[str, Any]) -> str:
    """Render the flat-table schema used by GKX runtime input files."""

    lines = ["# Generated by run_gkx_optimized_flux_scan.py."]
    tables = {
        key: value
        for key, value in data.items()
        if isinstance(value, dict)
        or (
            isinstance(value, list)
            and value
            and all(isinstance(item, dict) for item in value)
        )
    }
    for key, value in data.items():
        if key not in tables:
            lines.append(f"{key} = {_toml_value(value)}")
    for key, value in tables.items():
        items = value if isinstance(value, list) else [value]
        marker = f"[[{key}]]" if isinstance(value, list) else f"[{key}]"
        for item in items:
            lines.append("")
            lines.append(marker)
            lines.extend(f"{name} = {_toml_value(entry)}" for name, entry in item.items())
    return "\n".join(lines) + "\n"


def _default_gkx_root() -> Path:
    configured = os.environ.get("GKX_ROOT")
    if configured:
        return Path(configured).expanduser().resolve()
    neopax_root = Path(__file__).resolve().parents[2]
    sibling = neopax_root.parent / "GKX"
    if sibling.is_dir():
        return sibling.resolve()
    return (Path.home() / "GKX").resolve()


def _find_optimized_wout(output_folder: Path, explicit: Path | None) -> Path:
    if explicit is not None:
        path = explicit.expanduser().resolve()
        if not path.is_file():
            raise FileNotFoundError(f"Requested wout does not exist: {path}")
        return path

    optimized = output_folder / "optimized"
    search_root = optimized if optimized.is_dir() else output_folder
    candidates = sorted(
        path.resolve()
        for path in search_root.rglob("wout_*.nc")
        if not path.name.endswith((".out.nc", ".big.nc", ".restart.nc"))
        and "gkx" not in {part.lower() for part in path.parts}
    )
    preferred = [path for path in candidates if "optimized" in path.stem.lower()]
    if len(preferred) == 1:
        return preferred[0]
    if len(candidates) == 1:
        return candidates[0]
    if not candidates:
        raise FileNotFoundError(
            f"No optimized wout_*.nc was found below {search_root}. "
            "Generate the optimization plots/wout first or pass --wout."
        )
    choices = "\n  ".join(str(path) for path in candidates)
    raise ValueError(
        "More than one possible optimized wout was found; select one with --wout:\n"
        f"  {choices}"
    )


def _surface_tag(rho: float) -> str:
    return f"rho_{rho:.4f}".replace("-", "m").replace(".", "p")


def _load_template(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(
            f"GKX template was not found: {path}. Pass --template or --gkx-root."
        )
    with path.open("rb") as stream:
        data = tomllib.load(stream)
    species = data.get("species")
    if not isinstance(species, list) or len(species) != 1:
        raise ValueError(
            f"{path} must contain exactly one [[species]] block for this "
            "adiabatic-electron ion-temperature-gradient scan."
        )
    return data


def _prepare_deck(
    template: dict[str, Any],
    *,
    wout: Path,
    rho: float,
    torflux: float,
    t_max: float,
    tprim: float,
    fprim: float,
    run_dir: Path,
) -> tuple[Path, Path]:
    # Reload through JSON to copy this TOML-compatible tree without sharing
    # nested dictionaries between surfaces.
    data = json.loads(json.dumps(template))
    species = dict(data["species"][0])
    species.update(tprim=float(tprim), fprim=float(fprim), kinetic=True)
    data["species"] = [species]

    geometry = dict(data.get("geometry", {}))
    geometry.update(model="vmec", vmec_file=str(wout), torflux=float(torflux))
    geometry.pop("geometry_file", None)
    data["geometry"] = geometry

    physics = dict(data.get("physics", {}))
    physics.update(
        linear=False,
        nonlinear=True,
        adiabatic_electrons=True,
        adiabatic_ions=False,
    )
    data["physics"] = physics

    terms = dict(data.get("terms", {}))
    terms["nonlinear"] = 1.0
    data["terms"] = terms

    time = dict(data.get("time", {}))
    time.update(t_max=float(t_max), run_to="t_max")
    data["time"] = time

    output_path = (run_dir / "gkx.out.nc").resolve()
    output = dict(data.get("output", {}))
    output.update(
        path=str(output_path),
        restart_if_exists=True,
        save_for_restart=True,
        append_on_restart=True,
        plots=True,
    )
    data["output"] = output

    run_dir.mkdir(parents=True, exist_ok=True)
    deck_path = run_dir / "gkx.toml"
    deck_path.write_text(_toml_text(data), encoding="utf-8")
    metadata = {
        "rho": float(rho),
        "torflux_s": float(torflux),
        "wout": str(wout),
        "tprim_a_over_L_T": float(tprim),
        "fprim_a_over_L_n": float(fprim),
        "t_max_normalized": float(t_max),
        "deck": str(deck_path.resolve()),
        "output": str(output_path),
    }
    (run_dir / "scan_point.json").write_text(
        json.dumps(metadata, indent=2) + "\n", encoding="utf-8"
    )
    return deck_path.resolve(), output_path


def _last_saved_time(path: Path) -> float | None:
    if not path.is_file():
        return None
    try:
        from netCDF4 import Dataset

        with Dataset(path, "r") as root:
            values = root.groups["Grids"].variables["time"][:]
        import numpy as np

        finite = np.asarray(values, dtype=float)
        finite = finite[np.isfinite(finite)]
        return None if finite.size == 0 else float(finite[-1])
    except Exception:
        return None


def _run_deck(
    deck: Path,
    output: Path,
    *,
    t_max: float,
    gkx_root: Path,
    python: Path,
    rerun_complete: bool,
) -> None:
    saved_time = _last_saved_time(output)
    if (
        saved_time is not None
        and saved_time >= float(t_max) * (1.0 - 1.0e-7)
        and not rerun_complete
    ):
        print(f"[GKX scan] complete; skipping {deck.parent.name}: t={saved_time:.8g}")
        return

    env = os.environ.copy()
    source = str((gkx_root / "src").resolve())
    old_pythonpath = env.get("PYTHONPATH")
    env["PYTHONPATH"] = source if not old_pythonpath else source + os.pathsep + old_pythonpath
    command = [str(python), "-m", "gkx.cli", str(deck)]
    log_path = deck.parent / "gkx.log"
    print("[GKX scan] running " + " ".join(command), flush=True)
    with log_path.open("a", encoding="utf-8") as log:
        process = subprocess.Popen(
            command,
            cwd=deck.parent,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        assert process.stdout is not None
        for line in process.stdout:
            print(line, end="", flush=True)
            log.write(line)
            log.flush()
        return_code = process.wait()
    if return_code:
        raise subprocess.CalledProcessError(return_code, command)


def _read_heat_flux(path: Path):
    import numpy as np
    from netCDF4 import Dataset

    with Dataset(path, "r") as root:
        times = np.asarray(root.groups["Grids"].variables["time"][:], dtype=float)
        variable = root.groups["Diagnostics"].variables["HeatFlux_st"]
        heat = np.asarray(variable[:], dtype=float)
        dimensions = tuple(variable.dimensions)
    if "time" not in dimensions:
        raise ValueError(f"HeatFlux_st in {path} has no time axis: {dimensions}")
    time_axis = dimensions.index("time")
    heat = np.moveaxis(heat, time_axis, 0)
    if heat.ndim > 1:
        heat = np.sum(heat, axis=tuple(range(1, heat.ndim)))
    times = times.reshape(-1)
    heat = heat.reshape(-1)
    count = min(times.size, heat.size)
    finite = np.isfinite(times[:count]) & np.isfinite(heat[:count])
    if not np.any(finite):
        raise ValueError(f"No finite heat-flux samples were found in {path}")
    return times[:count][finite], heat[:count][finite]


def _plot_results(
    points: list[dict[str, Any]], *, output_dir: Path, average_fraction: float
) -> None:
    import matplotlib.pyplot as plt
    import numpy as np

    histories: list[dict[str, Any]] = []
    for point in points:
        path = Path(point["output"])
        if not path.is_file():
            raise FileNotFoundError(
                f"Missing GKX output for rho={point['rho']}: {path}. "
                "Run without --plot-only first."
            )
        time, flux = _read_heat_flux(path)
        window_start = float(time[-1] - average_fraction * (time[-1] - time[0]))
        window = time >= window_start
        histories.append(
            {
                **point,
                "time": time,
                "flux": flux,
                "window_start": window_start,
                "mean": float(np.mean(flux[window])),
                "std": float(np.std(flux[window])),
                "last": float(flux[-1]),
                "t_end": float(time[-1]),
                "samples": int(np.count_nonzero(window)),
            }
        )

    history_path = output_dir / "gkx_heat_flux_history.csv"
    with history_path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.writer(stream)
        writer.writerow(("rho", "torflux_s", "time", "ion_heat_flux"))
        for item in histories:
            for time, flux in zip(item["time"], item["flux"], strict=True):
                writer.writerow((item["rho"], item["torflux"], time, flux))

    summary_path = output_dir / "gkx_heat_flux_summary.csv"
    with summary_path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.writer(stream)
        writer.writerow(
            (
                "rho",
                "torflux_s",
                "t_end",
                "average_window_start",
                "average_samples",
                "ion_heat_flux_mean",
                "ion_heat_flux_std",
                "ion_heat_flux_last",
                "output",
            )
        )
        for item in histories:
            writer.writerow(
                (
                    item["rho"],
                    item["torflux"],
                    item["t_end"],
                    item["window_start"],
                    item["samples"],
                    item["mean"],
                    item["std"],
                    item["last"],
                    item["output"],
                )
            )

    figure, (time_axis, radius_axis) = plt.subplots(1, 2, figsize=(12.0, 4.6))
    colors = plt.cm.viridis(np.linspace(0.08, 0.92, len(histories)))
    for color, item in zip(colors, histories, strict=True):
        time_axis.plot(
            item["time"], item["flux"], color=color, linewidth=1.5,
            label=rf"$\rho={item['rho']:.1f}$",
        )
    time_axis.set_xlabel("GKX normalized time")
    time_axis.set_ylabel(r"Ion heat flux $Q_i$ [GKX normalization]")
    time_axis.legend(frameon=False, ncol=1)

    rho = np.asarray([item["rho"] for item in histories], dtype=float)
    means = np.asarray([item["mean"] for item in histories], dtype=float)
    stds = np.asarray([item["std"] for item in histories], dtype=float)
    radius_axis.errorbar(
        rho,
        means,
        yerr=stds,
        color="black",
        marker="o",
        markersize=5,
        linewidth=1.5,
        capsize=3,
    )
    radius_axis.set_xlabel(r"Normalized radius $\rho=\sqrt{s}$")
    radius_axis.set_ylabel(r"Late-time mean $Q_i$ [GKX normalization]")
    radius_axis.set_xticks(rho)
    figure.suptitle(
        rf"Adiabatic-electron GKX scan: $a/L_T={histories[0]['tprim']:g}$, "
        rf"$a/L_n={histories[0]['fprim']:g}$"
    )
    figure.tight_layout()
    figure_path = output_dir / "gkx_heat_flux_scan.png"
    figure.savefig(figure_path, dpi=300, bbox_inches="tight")
    plt.close(figure)

    print(f"wrote {history_path}")
    print(f"wrote {summary_path}")
    print(f"wrote {figure_path}")


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "output_folder",
        type=Path,
        help="NEOPAX optimization output folder containing optimized/wout_*.nc",
    )
    parser.add_argument("--wout", type=Path, help="Explicit optimized wout path")
    parser.add_argument("--gkx-root", type=Path, default=_default_gkx_root())
    parser.add_argument("--gkx-python", type=Path, default=Path(sys.executable))
    parser.add_argument("--template", type=Path)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--radii", type=float, nargs="+", default=DEFAULT_RADII)
    parser.add_argument(
        "--surface-coordinate",
        choices=("rho", "s"),
        default="rho",
        help="Interpret --radii as rho (default, torflux=rho^2) or directly as s",
    )
    parser.add_argument("--t-max", type=float, default=700.0)
    parser.add_argument("--tprim", type=float, default=3.0, help="Ion a/L_T")
    parser.add_argument("--fprim", type=float, default=0.0, help="Ion a/L_n")
    parser.add_argument(
        "--average-fraction",
        type=float,
        default=0.2,
        help="Final fraction of each trace used for the radial mean (default 0.2)",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--prepare-only", action="store_true")
    mode.add_argument("--plot-only", action="store_true")
    parser.add_argument(
        "--rerun-complete",
        action="store_true",
        help="Invoke GKX even when the saved trace has already reached t_max",
    )
    return parser


def main() -> int:
    args = _parser().parse_args()
    output_folder = args.output_folder.expanduser().resolve()
    if not output_folder.is_dir():
        raise FileNotFoundError(f"Optimization output folder does not exist: {output_folder}")
    if not 0.0 < args.average_fraction <= 1.0:
        raise ValueError("--average-fraction must lie in (0, 1]")
    if args.t_max <= 0.0:
        raise ValueError("--t-max must be positive")
    if not args.radii or any(not 0.0 < value < 1.0 for value in args.radii):
        raise ValueError("Every requested radius/surface must lie strictly inside (0, 1)")

    gkx_root = args.gkx_root.expanduser().resolve()
    template_path = (
        args.template.expanduser().resolve()
        if args.template is not None
        else gkx_root / "examples" / "common_input.toml"
    )
    wout = _find_optimized_wout(output_folder, args.wout)
    output_dir = (
        args.output_dir.expanduser().resolve()
        if args.output_dir is not None
        else output_folder / "optimized" / "gkx_adiabatic_electron_flux_scan"
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    template = _load_template(template_path)

    points: list[dict[str, Any]] = []
    for requested in args.radii:
        if args.surface_coordinate == "rho":
            rho, torflux = float(requested), float(requested) ** 2
        else:
            torflux, rho = float(requested), float(requested) ** 0.5
        run_dir = output_dir / _surface_tag(rho)
        deck, output = _prepare_deck(
            template,
            wout=wout,
            rho=rho,
            torflux=torflux,
            t_max=args.t_max,
            tprim=args.tprim,
            fprim=args.fprim,
            run_dir=run_dir,
        )
        points.append(
            {
                "rho": rho,
                "torflux": torflux,
                "tprim": float(args.tprim),
                "fprim": float(args.fprim),
                "deck": str(deck),
                "output": str(output),
            }
        )

    manifest = {
        "wout": str(wout),
        "template": str(template_path),
        "surface_coordinate_input": args.surface_coordinate,
        "t_max_normalized": float(args.t_max),
        "points": points,
    }
    manifest_path = output_dir / "gkx_flux_scan_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"[GKX scan] optimized wout: {wout}")
    print(f"[GKX scan] wrote {manifest_path}")

    if args.prepare_only:
        return 0
    if not args.plot_only:
        for point in points:
            _run_deck(
                Path(point["deck"]),
                Path(point["output"]),
                t_max=args.t_max,
                gkx_root=gkx_root,
                python=args.gkx_python.expanduser().resolve(),
                rerun_complete=args.rerun_complete,
            )
    _plot_results(points, output_dir=output_dir, average_fraction=args.average_fraction)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
